GET http://localhost:3000/profiles

###
GET http://localhost:3000/profiles/f957e14f33254a2098b8903891603678

###
POST http://localhost:3000/profiles/signup
Content-Type: application/json

{
  "email": "jdavault@example.com",
  "username": "jdavault01",
  "password": "p@55w0Rd01"
}

###
PUT http://localhost:3000/profiles/f957e14f33254a2098b8903891603678
Content-Type: application/json

{
  "email": "jdavault04@example.com",
  "username": "jdavault04",
  "password": "p@55w0Rd4"
}

###
DELETE http://localhost:3000/profiles/f957e14f33254a2098b8903891603678
